### ISSUE TITLE
feature enhancement todo list (add to the end by editing or commenting)

### ISSUE THREAD

**Issue by amoodie** [amoodie/rivers2stratigraphy#26]
- [ ] Use water discharge to determine sediment transport, and use this to affect the lateral migration rate and avulsion timescale
- [ ] Include option which has above as the default [`natural`], or allow `engineering` option to set both the avulsion timescale and the lateral mobility (total distance)
- [x] Rework the avulsion mechanic to calculate the concave hull. Alternatively, and easier, compute `convex hull` of every two sequential channel states and then compute `union` of these hulls. This should guarantee a `Polgyon` type (not `MultiPolygon`) and will look _more_ like the pure union objects.

**Comment by ericbarefoot** [comment]
I would be interested to see something like a "cross-cutting frequency" statistic. The interest here is to quantify the fact that channels in highly mobile settings and low subsidence settings often cut into other channel bodies. If this could be done stratigraphically, and this tool could show you how the distribution of crosscutting changes under a suite of circumstances could be pretty powerful.
